spring.application.name=turfbooking-backend

server.port=8080

# POSTGRESQL DATABASE CONFIGURATION

spring.datasource.url=jdbc:postgresql://localhost:5432/TurfBookingApplication
spring.datasource.username=postgres
spring.datasource.password=Aditya@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIGURATION

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT CONFIGURATION

jwt.secret=TurfBookingAppSecretKey2024!VeryLongSecretKeyForHMACSHA256Algorithm
jwt.expiration=86400000


# RAZORPAY CONFIGURATION (TEST MODE).
# Replace with your actual test keys from https://dashboard.razorpay.com

razorpay.key.id=rzp_test_SemCDXfZksZ89m
razorpay.key.secret=PbySlYZDowuFkA4Civk1EX6V


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method


logging.level.com.turfbooking=DEBUG
logging.level.org.springframework.security=INFO
